.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH TWMS 1 "June 29, 2010"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
twms \- tiny WMS server
.SH SYNOPSIS
.B twms
.I [PORT]
.br
.SH DESCRIPTION
This manual page documents briefly the
.B twms
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBtwms\fP is a tiny WMS server capable of serving tiled images or proxying another WMS services
.SH OPTIONS
The only optional parameter \fBtwms\fR accepts is the port number on which it listens.
Apart from that, it is fully configurable through its configuration file located at
\fI/etc/twms/twms.conf\fR. 
.br
.SH AUTHOR
twms was written by Darafei Praliaskouski <me@komzpa.net>.
.PP
This manual page was written by Andrew Shadura <bugzilla@tut.by>,
for the Debian project (and may be used by others).
